set nocompatible                  " Must come first because it changes other options.

if $SHELL =~ 'bin/fish'
  set shell=/bin/bash
endif

let mapleader = ","

" VUNDLE initialization
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

" Automatically close quotes, brackets, etc.
Bundle 'Raimondi/delimitMate'
Bundle 'tpope/vim-endwise'

" C-X + [space] in HTML insert mode
Bundle 'tpope/vim-ragtag'

" Snippets.
Bundle 'MarcWeber/vim-addon-mw-utils'
Bundle 'tomtom/tlib_vim'
Bundle 'garbas/vim-snipmate'

Bundle 'christhomson/vim-snippets'

Bundle 'bkad/CamelCaseMotion'
map <S-W> <Plug>CamelCaseMotion_w
map <S-B> <Plug>CamelCaseMotion_b
map <S-E> <Plug>CamelCaseMotion_e

" Git integration.
Bundle 'tpope/vim-fugitive'
if $LOCATION != "school"
  Bundle 'airblade/vim-gitgutter'
endif
Bundle 'gregsexton/gitv'
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gd :Gdiff<CR>


" Fuzzy file matcher.
" Looks to ancestor directories to find the source control root.
Bundle 'kien/ctrlp.vim'
let g:ctrlp_working_path_mode = 'r'
nnoremap <leader>p :CtrlP<CR>
nnoremap <leader>t :CtrlP<CR>

" Autocompletion.
Bundle 'Shougo/neocomplcache.vim'
let g:neocomplcache_enable_at_startup = 1
let g:neocomplcache_force_overwrite_completefunc=1

" Syntax checking on save.
Bundle 'scrooloose/syntastic'

" Fancy status line.
" You may need to install the patched font from
" https://github.com/Lokaltog/powerline-fonts
Bundle 'bling/vim-airline'
let g:airline#extensions#tabline#enabled = 1

" Find in project.
if executable('ag')
  Bundle 'rking/ag.vim'
  nnoremap <C-a> :Ag 
  nnoremap <leader>f :Ag 
  set grepprg=ag\ --nogroup\ --nocolor
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
  let g:ctrlp_use_caching = 0
elseif executable('ack')
  Bundle 'mileszs/ack.vim'
  nnoremap <C-f> :Ack
  nnoremap <leader>f :Ack
endif

" Ruby stuff.
Bundle 'tpope/vim-bundler'
Bundle 'tpope/vim-rake'
Bundle 'tpope/vim-rails'
Bundle 'tmhedberg/matchit'
Bundle 'ecomba/vim-ruby-refactoring'

" Easily rename files.
Bundle 'vim-scripts/Rename2'

" Tagbar uses ctags.
Bundle 'majutsushi/tagbar'
nnoremap <leader>b :TagbarOpenAutoClose<CR>

" Write boilerplate HTML inspired by CSS selectors
Bundle 'mattn/emmet-vim'
let g:user_emmet_install_global = 0
let g:user_emmet_leader_key='<C-e>' " <C-e>,

" Asynchronous tests, etc.
Bundle 'tpope/vim-dispatch'

Bundle 'tomtom/tcomment_vim'
map <leader>gc :TComment<CR>

Bundle 'chriskempson/vim-tomorrow-theme'
colorscheme Tomorrow-Night

" Language support.
Bundle 'plasticboy/vim-markdown'
let g:vim_markdown_folding_disabled=1

Bundle 'kchmck/vim-coffee-script'
au BufNewFile,BufRead *.coffee set filetype=coffee

Bundle 'hail2u/vim-css3-syntax'
Bundle 'cakebaker/scss-syntax.vim'
Bundle 'mustache/vim-mustache-handlebars'

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.
set backspace=indent,eol,start    " Intuitive backspacing.
set hidden                        " Handle multiple buffers better.
set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.
set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.
set number                        " Show line numbers.
set ruler                         " Show cursor position.
set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.
set wrap                          " Turn on line wrapping.
set linebreak
set scrolloff=12
set notitle                       " Set the terminal's title
set visualbell                    " No beeping.
set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp//,.  " Keep swap files in one location
set noswapfile                    " I like to live dangerously.
set laststatus=2                  " Show the status line all the time
set expandtab                     " Use spaces for tabs.
set shiftwidth=2
set softtabstop=2                 " 2 spaces is a tab.
set updatetime=750
set autoread
set cursorline
set list listchars=tab:»·,trail:· " Show extra whitespace.
set nofoldenable

highlight CursorLine cterm=none ctermbg=0

let &t_Co=256

" Makes Vim recognize empty .tex files properly as tex files instead of
" plaintex files.
let g:tex_flavor='latex'
let g:Tex_ViewRule_pdf = 'open -a Skim'
let g:Imap_UsePlaceHolders = 0 " disable <++> markers
"let g:Tex_CompileRule_pdf = 'xelatex --interaction=nonstopmode $*'

cmap w!! %!sudo tee > /dev/null %   " Force save, if you forgot to sudo when needed

" Ignore patterns for autocompletion.
set wildignore=*.o,*.obj,*~,*sass-cache*,*DS_Store*,*/log/**,*/tmp/**,*.png,*.jpg,*.gif,*node_modules*

nnoremap <silent><Tab> :bn<CR>
nnoremap <silent><S-Tab> :bp<CR>
nnoremap <silent><Leader>d :bd<CR>
nnoremap <silent>U :redo<CR>

" Automatically reload changes you make to .vimrc.
autocmd BufWritePost ~/.vimrc source ~/.vimrc
autocmd BufWritePost ~/.config/vimrc source ~/.vimrc

" Overrides for specific filetypes.
autocmd FileType ruby setlocal shiftwidth=2 tabstop=2
autocmd FileType gitcommit setlocal spell textwidth=72
autocmd FileType tex setlocal spell
autocmd FileType mkd setlocal spell
autocmd FileType html,css,scss EmmetInstall
autocmd FileType vim let b:loaded_delimitMate=0
autocmd FileType html,eruby let b:closetag_html_style=1
autocmd FileType text,mkd setlocal textwidth=80

syntax enable                     " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.
