alias ..='cd ..'
alias b='bundle'
alias be='bundle exec'
alias bc='bundle exec rails console'
alias bs='bundle exec rails server'
alias bi='bundle install'
alias bake='bundle exec rake'
alias bails='bundle exec rails'
alias gs='git st'
alias gst='git st'
alias gd='git diff'
alias vi='vim'
alias gbrt='git branch-timeline'

# Don't log these in my history.
alias ls=' ls'
alias cd=' cd'
