ZSH=$HOME/.config/zsh
export EDITOR=vim

source $ZSH/antigen/antigen.zsh

antigen-use oh-my-zsh

antigen-bundle brew
antigen-bundle gitfast
antigen-bundle npm
antigen-bundle vagrant

if [ `uname`="Darwin" ]; then
  antigen-bundle osx
  antigen-bundle sublime
fi

antigen-bundle zsh-users/zsh-syntax-highlighting
antigen-theme $ZSH/themes/chris-arrow.zsh-theme
antigen-apply

export LOCATION="anywhere"

if [[ `hostname` =~ linux0[0-9][0-9]\.student\.cs ]]; then
  LOCATION="school"
fi

# Don't annoy me as much as you'd like to.
export UPDATE_ZSH_DAYS=30 
export DISABLE_UPDATE_PROMPT=true

export COMPLETION_WAITING_DOTS="true"

source $ZSH/machine.zsh
source $ZSH/aliases.zsh
source $ZSH/path.zsh

bindkey -e
bindkey '^[[1;9C' forward-word
bindkey '^[[1;9D' backward-word

if which rbenv &>/dev/null ; then
  source $ZSH/rbenv.zsh
fi
