ZSH=$HOME/dotfiles/zsh
export EDITOR=vim

export LOCATION="anywhere"

source $ZSH/antigen.zsh

antigen use oh-my-zsh

antigen bundle gitfast

if [ `uname`="Darwin" ]; then
  export OSX=1
  antigen bundle osx
  antigen bundle sublime
fi

antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle woefe/git-prompt.zsh
antigen apply

# Don't annoy me as much as you'd like to.
export UPDATE_ZSH_DAYS=30
export DISABLE_UPDATE_PROMPT=true

export COMPLETION_WAITING_DOTS="true"

source $ZSH/aliases.zsh
source $ZSH/path.zsh
source $ZSH/functions.zsh

export KEYTIMEOUT=1

setopt HIST_IGNORE_SPACE
setopt HIST_IGNORE_DUPS

foreground-vi() {
  fg %vi
}

zle -N foreground-vi
bindkey '^Z' foreground-vi

zstyle ':completion:*:processes-names' command 'ps -e -o comm='

setopt nohistverify

export PRY=1

[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

export NVM_DIR="/Users/chris/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# load dev, but only if present and the shell is interactive
if [[ -f /opt/dev/dev.sh ]] && [[ $- == *i* ]]; then
  source /opt/dev/dev.sh
fi

if [[ -f /usr/local/share/chruby/chruby.sh ]]; then
  source /usr/local/share/chruby/chruby.sh
fi

# export JAVA_HOME=`/usr/libexec/java_home -v 1.8`

export PATH="$HOME/.yarn/bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.antigen/bundles/woefe/git-prompt.zsh/examples/rprompt.zsh
export ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg_no_bold[green]%}"

export PROMPT_COMMAND='echo -ne "\033]0;$PWD\007"'
export PATH=$GOPATH/bin:$PATH
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
export PATH="/usr/local/opt/mysql-client/bin:$PATH"

export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
if [ -e /Users/chris/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/chris/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
