ZSH=$HOME/.config/zsh

source $ZSH/antigen/antigen.zsh

antigen-use oh-my-zsh

antigen-bundle brew
antigen-bundle bundler
antigen-bundle gitfast
antigen-bundle npm
antigen-bundle rails
antigen-bundle vagrant

if [ `uname`="Darwin" ]; then
  antigen-bundle osx
  antigen-bundle sublime
fi

antigen-bundle zsh-users/zsh-syntax-highlighting
antigen-theme $ZSH/themes/chris-arrow.zsh-theme
antigen-apply

export LOCATION="anywhere"

if [[ `hostname` =~ linux0[0-9][0-9]\.student\.cs ]]; then
  LOCATION="school"
fi

# Don't annoy me as much as you'd like to.
export UPDATE_ZSH_DAYS=45 

export COMPLETION_WAITING_DOTS="true"

source $ZSH/machine.zsh
source $ZSH/aliases.zsh
source $ZSH/path.zsh

if [ `rbenv --version >/dev/null 2>&1` ]; then
  source $ZSH/rbenv.zsh
fi
